import yaml

# Load config file
with open('param.yaml', 'r') as file:
    config = yaml.safe_load(file)

PSO_PARAMS = config['PSO']
# CONSTRAINTS = config['CONSTRAINTS']
DATASET = config['DATASET']
# Problem
INSTANCE = DATASET['INSTANCE']
DATA_PATH = DATASET['DATA_PATH']

# PSO hyperparameters
# POPULATION_SIZE = PSO_PARAMS['POPULATION_SIZE']
# MAX_ITER = PSO_PARAMS['MAX_ITER']
# COGNITIVE_WEIGHT = PSO_PARAMS['COGNITIVE_WEIGHT']
# SOCIAL_WEIGHT = PSO_PARAMS['SOCIAL_WEIGHT']
# INFEASIBILITY_PENALTY = PSO_PARAMS['INFEASIBILITY_PENALTY']
# INERTIA = PSO_PARAMS['INERTIA']