experiment:
  samples:
    # small:
    #   instances:
    #     - "C101_co_25.txt"
    #     # - "R101_co_25.txt"
    #     # - "RC101_co_25.txt"
    #   data_dir: "data/25"
    # medium:
    #   instances:
    #     - "C101_co_50.txt"
    #     # - "R101_co_50.txt"
    #     # - "RC101_co_50.txt"
    #   data_dir: "data/50"
    large:
      instances:
        - "C101_co_100.txt"
        # - "R101_co_100.txt"
        # - "RC101_co_100.txt"
      data_dir: "data/100"
  num_runs: 1
  max_cores: 64
  core_counts: [1, 8, 16, 32, 64]
  output_dir: "output/speedup_analysis"
  paco_params:
    num_iterations: 50
    num_ants: 1024
    alpha: 1.0
    beta: 2.0
    evaporation_rate: 0.2
    Q: 1.0
    elitist_num: 50
  saco_params:
    num_ants: 1000
    num_iterations: 100
    alpha: 1.0
    beta: 2.0
    evaporation_rate: 0.2
    Q: 1.0
    elitist_num: 10