small:
  data_dir: data/25
  paco_params:
    num_ants: 256
    num_iterations: 25
    batch_size: 64
    alpha: 1.0
    beta: 1.0
    evaporation_rate: 0.4
    Q: 1.0
    elitist_num: 10
  num_runs: 20
  output_csv: output/solutions/small.csv

medium:
  data_dir: data/50
  paco_params:
    num_ants: 512
    num_iterations: 20
    batch_size: 16
    alpha: 1.0
    beta: 1.0
    evaporation_rate: 0.44
    Q: 1.0
    elitist_num: 20
  num_runs: 20
  output_csv: output/solutions/medium.csv

large:
  data_dir: data/100
  paco_params:
    num_ants: 3200
    num_iterations: 35
    batch_size: 50
    alpha: 1.0
    beta: 1.0
    evaporation_rate: 0.44
    Q: 1.0
    elitist_num: 30
  num_runs: 20
  output_csv: output/solutions/large.csv