# small:
#   data_dir: data/25
#   paco_params:
#     num_ants: 128
#     num_iterations: 25
#     batch_size: 4
#     alpha: 1.0
#     beta: 1.0
#     evaporation_rate: 0.4
#     Q: 1.0
#     elitist_num: 4
#   num_runs: 5
#   output_csv: output/small_experiment.csv

# medium:
#   data_dir: data/50
#   paco_params:
#     num_ants: 200
#     num_iterations: 50
#     batch_size: 20
#     alpha: 1.0
#     beta: 1.0
#     evaporation_rate: 0.2
#     Q: 1.0
#     elitist_num: 10
#   num_runs: 3
#   output_csv: output/medium_experiment.csv

large:
  data_dir: data/100
  paco_params:
    num_ants: 3200
    num_iterations: 30
    batch_size: 50
    alpha: 1.0
    beta: 1.0
    evaporation_rate: 0.44
    Q: 1.0
    elitist_num: 10
  num_runs: 5
  output_csv: output/large_complete.csv